// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     OssTask.avsc
 */

package PhOssTask

import (
	"github.com/actgardner/gogen-avro/compiler"
	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type OssTask struct {
	TitleIndex []int32
	JobId      string
	TraceId    string
	OssKey     string
	FileType   string
	FileName   string
	SheetName  string
	Labels     []string
	DataCover  []string
	GeoCover   []string
	Markets    []string
	Molecules  []string
	Providers  []string
}

func NewOssTaskWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &OssTask{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func DeserializeOssTask(r io.Reader) (*OssTask, error) {
	t := NewOssTask()
	err := deserializeField(r, t.Schema(), t.Schema(), t)
	return t, err
}

func DeserializeOssTaskFromSchema(r io.Reader, schema string) (*OssTask, error) {
	t := NewOssTask()
	err := deserializeField(r, schema, t.Schema(), t)
	return t, err
}

func NewOssTask() *OssTask {
	return &OssTask{}
}

func (r *OssTask) Schema() string {
	return "{\"fields\":[{\"name\":\"titleIndex\",\"type\":{\"items\":\"int\",\"type\":\"array\"}},{\"name\":\"jobId\",\"type\":\"string\"},{\"name\":\"traceId\",\"type\":\"string\"},{\"name\":\"ossKey\",\"type\":\"string\"},{\"name\":\"fileType\",\"type\":\"string\"},{\"name\":\"fileName\",\"type\":\"string\"},{\"name\":\"sheetName\",\"type\":\"string\"},{\"name\":\"labels\",\"type\":{\"items\":\"string\",\"type\":\"array\"}},{\"name\":\"dataCover\",\"type\":{\"items\":\"string\",\"type\":\"array\"}},{\"name\":\"geoCover\",\"type\":{\"items\":\"string\",\"type\":\"array\"}},{\"name\":\"markets\",\"type\":{\"items\":\"string\",\"type\":\"array\"}},{\"name\":\"molecules\",\"type\":{\"items\":\"string\",\"type\":\"array\"}},{\"name\":\"providers\",\"type\":{\"items\":\"string\",\"type\":\"array\"}}],\"name\":\"OssTask\",\"namespace\":\"com.pharbers.kafka.schema\",\"type\":\"record\"}"
}

func (r *OssTask) SchemaName() string {
	return "com.pharbers.kafka.schema.OssTask"
}

func (r *OssTask) Serialize(w io.Writer) error {
	return writeOssTask(r, w)
}

func (_ *OssTask) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *OssTask) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *OssTask) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *OssTask) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *OssTask) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *OssTask) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *OssTask) SetString(v string)   { panic("Unsupported operation") }
func (_ *OssTask) SetUnionElem(v int64) { panic("Unsupported operation") }
func (r *OssTask) Get(i int) types.Field {
	switch i {
	case 0:
		r.TitleIndex = make([]int32, 0)
		return (*ArrayIntWrapper)(&r.TitleIndex)
	case 1:
		return (*types.String)(&r.JobId)
	case 2:
		return (*types.String)(&r.TraceId)
	case 3:
		return (*types.String)(&r.OssKey)
	case 4:
		return (*types.String)(&r.FileType)
	case 5:
		return (*types.String)(&r.FileName)
	case 6:
		return (*types.String)(&r.SheetName)
	case 7:
		r.Labels = make([]string, 0)
		return (*ArrayStringWrapper)(&r.Labels)
	case 8:
		r.DataCover = make([]string, 0)
		return (*ArrayStringWrapper)(&r.DataCover)
	case 9:
		r.GeoCover = make([]string, 0)
		return (*ArrayStringWrapper)(&r.GeoCover)
	case 10:
		r.Markets = make([]string, 0)
		return (*ArrayStringWrapper)(&r.Markets)
	case 11:
		r.Molecules = make([]string, 0)
		return (*ArrayStringWrapper)(&r.Molecules)
	case 12:
		r.Providers = make([]string, 0)
		return (*ArrayStringWrapper)(&r.Providers)

	}
	panic("Unknown field index")
}
func (r *OssTask) SetDefault(i int) {
	switch i {

	}
	panic("Unknown field index")
}
func (_ *OssTask) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *OssTask) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *OssTask) Finalize()                        {}

type OssTaskReader struct {
	r io.Reader
	p *vm.Program
}

func NewOssTaskReader(r io.Reader) (*OssTaskReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewOssTask()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &OssTaskReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r *OssTaskReader) Read() (*OssTask, error) {
	t := NewOssTask()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
