// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     Job.avsc
 */

package PhJob

import (
	"github.com/actgardner/gogen-avro/compiler"
	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type Job struct {
	JobId       string
	Status      string
	Error       string
	Description string
}

func NewJobWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &Job{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func DeserializeJob(r io.Reader) (*Job, error) {
	t := NewJob()
	err := deserializeField(r, t.Schema(), t.Schema(), t)
	return t, err
}

func DeserializeJobFromSchema(r io.Reader, schema string) (*Job, error) {
	t := NewJob()
	err := deserializeField(r, schema, t.Schema(), t)
	return t, err
}

func NewJob() *Job {
	return &Job{}
}

func (r *Job) Schema() string {
	return "{\"fields\":[{\"name\":\"jobId\",\"type\":\"string\"},{\"name\":\"status\",\"type\":\"string\"},{\"name\":\"error\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"}],\"name\":\"Job\",\"namespace\":\"com.pharbers.kafka.schema\",\"type\":\"record\"}"
}

func (r *Job) SchemaName() string {
	return "com.pharbers.kafka.schema.Job"
}

func (r *Job) Serialize(w io.Writer) error {
	return writeJob(r, w)
}

func (_ *Job) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *Job) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *Job) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *Job) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *Job) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *Job) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *Job) SetString(v string)   { panic("Unsupported operation") }
func (_ *Job) SetUnionElem(v int64) { panic("Unsupported operation") }
func (r *Job) Get(i int) types.Field {
	switch i {
	case 0:
		return (*types.String)(&r.JobId)
	case 1:
		return (*types.String)(&r.Status)
	case 2:
		return (*types.String)(&r.Error)
	case 3:
		return (*types.String)(&r.Description)

	}
	panic("Unknown field index")
}
func (r *Job) SetDefault(i int) {
	switch i {

	}
	panic("Unknown field index")
}
func (_ *Job) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Job) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *Job) Finalize()                        {}

type JobReader struct {
	r io.Reader
	p *vm.Program
}

func NewJobReader(r io.Reader) (*JobReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewJob()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &JobReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r *JobReader) Read() (*Job, error) {
	t := NewJob()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
