// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     OssTask.avsc
 */

package Record

import (
	"github.com/actgardner/gogen-avro/compiler"
	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type OssTask struct {
	JobId    string
	TraceId  string
	OssKey   string
	FileType string
}

func NewOssTaskWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &OssTask{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func DeserializeOssTask(r io.Reader) (*OssTask, error) {
	t := NewOssTask()
	err := deserializeField(r, t.Schema(), t.Schema(), t)
	return t, err
}

func DeserializeOssTaskFromSchema(r io.Reader, schema string) (*OssTask, error) {
	t := NewOssTask()
	err := deserializeField(r, schema, t.Schema(), t)
	return t, err
}

func NewOssTask() *OssTask {
	return &OssTask{}
}

func (r *OssTask) Schema() string {
	return "{\"fields\":[{\"name\":\"jobId\",\"type\":\"string\"},{\"name\":\"traceId\",\"type\":\"string\"},{\"name\":\"ossKey\",\"type\":\"string\"},{\"name\":\"fileType\",\"type\":\"string\"}],\"name\":\"OssTask\",\"namespace\":\"com.pharbers.kafka.schema\",\"type\":\"record\"}"
}

func (r *OssTask) SchemaName() string {
	return "com.pharbers.kafka.schema.OssTask"
}

func (r *OssTask) Serialize(w io.Writer) error {
	return writeOssTask(r, w)
}

func (_ *OssTask) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *OssTask) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *OssTask) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *OssTask) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *OssTask) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *OssTask) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *OssTask) SetString(v string)   { panic("Unsupported operation") }
func (_ *OssTask) SetUnionElem(v int64) { panic("Unsupported operation") }
func (r *OssTask) Get(i int) types.Field {
	switch i {
	case 0:
		return (*types.String)(&r.JobId)
	case 1:
		return (*types.String)(&r.TraceId)
	case 2:
		return (*types.String)(&r.OssKey)
	case 3:
		return (*types.String)(&r.FileType)

	}
	panic("Unknown field index")
}
func (r *OssTask) SetDefault(i int) {
	switch i {

	}
	panic("Unknown field index")
}
func (_ *OssTask) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *OssTask) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *OssTask) Finalize()                        {}

type OssTaskReader struct {
	r io.Reader
	p *vm.Program
}

func NewOssTaskReader(r io.Reader) (*OssTaskReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewOssTask()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &OssTaskReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r *OssTaskReader) Read() (*OssTask, error) {
	t := NewOssTask()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
